### PR TITLE
feat: jazz up the output

### PR DESCRIPTION
**Pull request by cagiti**
image

### CODE REVIEW

**Comment by garethjevans** [comment]
@cagiti do you think we should add a NO_COLOR=true option?

**Comment by cagiti** [comment]
> @cagiti do you think we should add a NO_COLOR=true option?

yeah, makes sense actually 👍

**Comment by garethjevans** [comment]
@cagiti happy for this to go in?

**Comment by cagiti** [comment]
@garethjevans: think a `--no-color` option is required?

**Pull request merged**
